services:
  - type: web
    name: market-planner
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
