services:
  - type: web
    name: market-planner
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_URL
        value: "mysql://31PBZEhPFXLyVbp.e2a108d9e1ae:7HLuq0091df4UYaLpALp@gateway06.us-east-1.prod.aws.tidbcloud.com:4000/Es4BvchFRGcgYYcUzKQNbt?ssl={\"rejectUnauthorized\":true}"
