import type { TaskCategory, TaskStatus } from "../drizzle/schema";

export type SeedTaskItem = {
  title: string;
  category: TaskCategory;
  description?: string;
  notes?: string;
  status: TaskStatus;
  dueDate?: Date;
  sortOrder: number;
};

export const OFFICIAL_TIMELINE_TASKS: SeedTaskItem[] = [
  // ==================== 05月：戰略開發與市場洞察月 ====================
  {
    title: "BMC 商業九宮格建模（鎖定核心價值與獲利模式）",
    category: "curation",
    description: "完成「商業九宮格」實戰，鎖定核心價值主張（Why us?），確立獲利模式與成本結構，確保獲利邏輯成立。",
    notes: "重點產出：商業九宮格 (BMC) 最終確認表，鎖定設計背景核心優勢。",
    status: "done",
    dueDate: new Date("2026-05-31"),
    sortOrder: 1,
  },
  {
    title: "SWOT 競爭優勢分析（設計背景 vs 現有策展公司）",
    category: "curation",
    description: "評估團隊的設計背景（室內設計/統包實力）相對於現有策展公司的競爭優勢與市場缺口。",
    notes: "重點產出：SWOT 競爭優勢分析報告。",
    status: "done",
    dueDate: new Date("2026-05-31"),
    sortOrder: 2,
  },
  {
    title: "指標市集田野考察（走訪 3-5 場量化記錄）",
    category: "curation",
    description: "實際走訪 3-5 個指標性市集，記錄人流量、預估客單價、攤商滿意度、現場動線安排與攤位配置細節。",
    notes: "重點產出：3-5 份指標市集市場研究與量化數據報告。",
    status: "done",
    dueDate: new Date("2026-05-31"),
    sortOrder: 3,
  },
  {
    title: "建立共同資料庫與市場研究檢核表",
    category: "curation",
    description: "建立團隊共同資料庫與檢核紀錄表，將考察結果轉化為系統化市場研究報告。",
    notes: "避免未來因主觀感覺爭吵，以數據做為決策基礎。",
    status: "done",
    dueDate: new Date("2026-05-31"),
    sortOrder: 4,
  },
  {
    title: "簽署共同創辦人協議（組織章程確立）",
    category: "curation",
    description: "正式簽署「共同創辦人協議（組織章程）」，明確股權比例、權利義務與退場機制，確保團隊穩定性。",
    notes: "已簽署之「共同創辦人協議」正本備查。",
    status: "done",
    dueDate: new Date("2026-05-31"),
    sortOrder: 5,
  },

  // ==================== 06月：品牌實體化與社群啟動月 ====================
  {
    title: "品牌視覺識別系統 (CIS) 定調與 Logo 設計",
    category: "design",
    description: "建立品牌基礎視覺，包含 Logo 設計、標準色、輔助圖形與字體規範手冊。",
    notes: "重點產出：品牌視覺手冊 (Logo, 字體, 標準色)。發揮團隊設計強項。",
    status: "in_progress",
    dueDate: new Date("2026-06-30"),
    sortOrder: 6,
  },
  {
    title: "品牌論述撰寫與 Slogan 定位（Brand Story）",
    category: "marketing",
    description: "撰寫品牌故事（Brand Story）與有力度的 Slogan，定義高質感、設計感之品牌調性。",
    notes: "定義品牌靈魂（Why us?），作為對外溝通與招商門面。",
    status: "done",
    dueDate: new Date("2026-06-30"),
    sortOrder: 7,
  },
  {
    title: "官方社群平台創立與設定 (IG / FB / Threads)",
    category: "marketing",
    description: "正式開通 IG 與 FB 官方帳號，設定統一的品牌識別與排版風格。",
    notes: "官方社群平台 (IG/FB) 形象建立。",
    status: "in_progress",
    dueDate: new Date("2026-06-30"),
    sortOrder: 8,
  },
  {
    title: "發布品牌誕生紀錄（第一波社群內容）",
    category: "marketing",
    description: "發布籌備幕後、團隊理念、考察心得等內容，讓觀眾參與品牌的成長過程，累積第一批種子粉絲。",
    notes: "重點產出：官方社群平台第一波發文內容清單。",
    status: "in_progress",
    dueDate: new Date("2026-06-30"),
    sortOrder: 9,
  },
  {
    title: "策展願景藍圖與理想規劃草案",
    category: "curation",
    description: "將品牌願景轉化為具體的策展規劃草案，作為後續招募與場地洽談的基礎。",
    notes: "作為後續向場地方接洽之提案基礎。",
    status: "done",
    dueDate: new Date("2026-06-30"),
    sortOrder: 10,
  },

  // ==================== 07月：法律架構與營運規範月 ====================
  {
    title: "股權協議正式簽署（51% 絕對主導權與否決權）",
    category: "curation",
    description: "簽署具法律效力之協議，確立發起人持有 51% 股份，擁有人事、財務與戰略決策主導權，明確一票否決權適用範圍。",
    notes: "重點產出：已公證/簽署之股權協議書（含 51% 條款）。",
    status: "in_progress",
    dueDate: new Date("2026-07-31"),
    sortOrder: 11,
  },
  {
    title: "財務分配機制設定（公積金、勞務津貼、年度分紅）",
    category: "curation",
    description: "制定盈餘分配規則：提撥公積金應對風險、訂定專案成員勞務津貼核發規則、股東年度淨利分紅比例與時間點。",
    notes: "明確「做多少事領多少津貼」與「年底分紅」規則，避免爭議。",
    status: "in_progress",
    dueDate: new Date("2026-07-31"),
    sortOrder: 12,
  },
  {
    title: "草擬市集招商規範手冊（報名資格與攤位規格）",
    category: "vendor",
    description: "建立招商手冊初稿，包含報名資格、攤位規格、用電瓦數限制、禁止事項與現場規範。",
    notes: "為後續招商文件建立標準。",
    status: "in_progress",
    dueDate: new Date("2026-07-31"),
    sortOrder: 13,
  },
  {
    title: "攤商合作合約書與退費違約機制制定",
    category: "vendor",
    description: "撰寫攤商合作法律合約，明確定義保證金規範、退費機制與違約罰則。",
    notes: "重點產出：攤商合作合約書（含退費及雨天對策）。",
    status: "pending",
    dueDate: new Date("2026-07-31"),
    sortOrder: 14,
  },
  {
    title: "雨天備案對策與公共意外責任險評估",
    category: "operation",
    description: "制定雨天延期配套、現場防雨設備規劃，並諮詢評估公共意外責任險投保額度。",
    notes: "確保天候風險可控，活動具備應變能力。",
    status: "pending",
    dueDate: new Date("2026-07-31"),
    sortOrder: 15,
  },
  {
    title: "市場理想規劃修正與長期趨勢追蹤",
    category: "curation",
    description: "根據 5-6 月考察報告與田野調查，持續修正商業計畫書，進行長期的市場動態與策展趨勢追蹤。",
    notes: "動態微調商業模式與活動亮點定位。",
    status: "in_progress",
    dueDate: new Date("2026-07-31"),
    sortOrder: 16,
  },

  // ==================== 08月：公司設立與戰術執行月 ====================
  {
    title: "公司行號登記申請與開立官方銀行帳戶",
    category: "curation",
    description: "正式申請公司行號登記（有限公司或商業登記），開立官方公款銀行帳戶，公私帳務徹底分離。",
    notes: "重點產出：公司行號登記核准函、大小章與官方存摺。",
    status: "in_progress",
    dueDate: new Date("2026-08-31"),
    sortOrder: 17,
  },
  {
    title: "首展 Top 3 場地名單篩選與 P&L 損益初估",
    category: "curation",
    description: "針對學校、商圈、戶外場地篩選適合首展的 Top 3 名單，進行租金、硬體、行銷損益初估報告。",
    notes: "重點產出：首場活動場地分析表與預算初估報告。",
    status: "in_progress",
    dueDate: new Date("2026-08-31"),
    sortOrder: 18,
  },
  {
    title: "模擬擺攤測試（測試硬體穩定度、動線與陳列）",
    category: "design",
    description: "團隊內部進行實戰模擬擺攤測試，檢驗攤位陳列美感、動線流速與硬體結構穩定度，發揮設計強項。",
    notes: "發揮室內設計與統包專業優勢。",
    status: "pending",
    dueDate: new Date("2026-08-31"),
    sortOrder: 19,
  },
  {
    title: "社群深度經營（發布品牌故事系列與視覺調性統一）",
    category: "marketing",
    description: "統一社群圖文濾鏡與高端排版調性，持續發布創業故事與品牌核心價值（Why us?），吸引理念相同的優質攤友。",
    notes: "重點產出：品牌 IG/FB 形象牆（含品牌故事系列文）。",
    status: "in_progress",
    dueDate: new Date("2026-08-31"),
    sortOrder: 20,
  },
  {
    title: "8月實體會議與市集實地考察（確認首場市集主題與呈現方式）",
    category: "curation",
    description: "組織團隊全員實體會議逛指標市集，深入討論並定案第一次市集主題名稱、空間呈現風格與品牌亮點。",
    notes: "關鍵里程碑：8月實體會議確認市集主題與現場氛圍定調！",
    status: "in_progress",
    dueDate: new Date("2026-08-31"),
    sortOrder: 21,
  },

  // ==================== 09月：場地攻堅與供應鏈整合月 ====================
  {
    title: "場地實地接洽與簽約（確認限制與避開大考連假）",
    category: "curation",
    description: "實地拜訪目標場地（學校/商圈/戶外），詳列音量分貝、用電瓦數上限、撤場時限與租金費用，避開大考與連假。",
    notes: "重點產出：已簽署之場地租借合約。",
    status: "pending",
    dueDate: new Date("2026-09-30"),
    sortOrder: 22,
  },
  {
    title: "基礎設施供應鏈整合與詢價發包",
    category: "operation",
    description: "針對電力配置、流動廁所、垃圾清運、棚架帳篷、桌椅硬體進行多家詢價與發包。",
    notes: "重點產出：協力廠商聯繫清冊 (含電力、清潔、硬體)。",
    status: "pending",
    dueDate: new Date("2026-09-30"),
    sortOrder: 23,
  },
  {
    title: "水電技術串接與攤位電力配電邏輯討論",
    category: "operation",
    description: "根據場地電力配置圖，與水電技師討論各攤位總用電瓦數與迴路分配邏輯，防止跳電。",
    notes: "用電安全是市集成功的關鍵基本功。",
    status: "pending",
    dueDate: new Date("2026-09-30"),
    sortOrder: 24,
  },

  // ==================== 10月：招商備戰與活動內容定案月 ====================
  {
    title: "製作極具設計感之招商簡章 (Final Deck & 3D透視)",
    category: "design",
    description: "結合工作室設計力，製作視覺吸睛、邏輯清晰之招商計畫書，加入攤位模擬透視圖與 3D 動線規劃，展現專業度。",
    notes: "重點產出：極具設計感之招商簡章 (Final Deck)。",
    status: "pending",
    dueDate: new Date("2026-10-31"),
    sortOrder: 25,
  },
  {
    title: "市集規範書最終版確認 (PDF 規範)",
    category: "vendor",
    description: "確定《市集規範書》最終版內容，包含違規罰則、美學陳列要求及進撤場作業流程。",
    notes: "重點產出：市集規範書 (確認版 PDF)。",
    status: "pending",
    dueDate: new Date("2026-10-31"),
    sortOrder: 26,
  },
  {
    title: "建立潛在商家口袋名單與業種黃金配比",
    category: "vendor",
    description: "主動聯繫符合質感的指標攤位，規劃餐飲、手作創意、互動體驗之黃金比例，確保市集豐富度。",
    notes: "重點產出：攤商招募篩選機制與配比圖。",
    status: "pending",
    dueDate: new Date("2026-10-31"),
    sortOrder: 27,
  },
  {
    title: "活動特殊亮點設計（現場表演 / 體驗課 / 打卡裝置）",
    category: "curation",
    description: "規劃當日特殊軟體亮點（如：現場音樂表演、手作體驗工作坊、策展主題打卡裝置），增加活動厚度。",
    notes: "重點產出：活動內容流程企劃書。",
    status: "pending",
    dueDate: new Date("2026-10-31"),
    sortOrder: 28,
  },
  {
    title: "建立例行週會與專案檢核機制（貫穿 9-10 月）",
    category: "curation",
    description: "落實週會與進度檢核，使用專案工具維持各組資訊透明，確保事事有交代、件件有落實。",
    notes: "全體成員保持進度穩定與溝通暢通。",
    status: "in_progress",
    dueDate: new Date("2026-10-31"),
    sortOrder: 29,
  },

  // ==================== 11月：招商與行銷啟動月 ====================
  {
    title: "正式開放攤商報名與發放招商簡章",
    category: "vendor",
    description: "發放正式招商簡章與報名表單，全面開放潛在攤友報名。",
    notes: "重點產出：攤商招募簡章與報名表單。",
    status: "pending",
    dueDate: new Date("2026-11-30"),
    sortOrder: 30,
  },
  {
    title: "執行嚴格攤商徵選與審查（月底產出名單）",
    category: "vendor",
    description: "執行嚴格徵選審核制度，確保入選攤位符合品牌美學與質感定位，於月底前完成初步篩選。",
    notes: "重點產出：入選攤商名單初稿。",
    status: "pending",
    dueDate: new Date("2026-11-30"),
    sortOrder: 31,
  },
  {
    title: "市集活動主視覺公開與宣傳短片拍攝籌備",
    category: "marketing",
    description: "正式公開市集品牌形象與活動主視覺，啟動宣傳短片拍攝與後期製作。",
    notes: "重點產出：活動宣傳主視覺與短片素材。",
    status: "pending",
    dueDate: new Date("2026-11-30"),
    sortOrder: 32,
  },
  {
    title: "預算損益表 (P&L) 即時核對更新",
    category: "curation",
    description: "根據招商實際收入與硬體開銷，動態調整損益表與成本預算。",
    notes: "重點產出：預算損益表 (P&L) 更新版。",
    status: "pending",
    dueDate: new Date("2026-11-30"),
    sortOrder: 33,
  },

  // ==================== 12月：行銷與品牌擴散月 ====================
  {
    title: "啟動多平台社群經營矩陣 (IG / Threads)",
    category: "marketing",
    description: "制定每週發文計畫，定期釋出攤商介紹、策展理念與籌備花絮，營造期待感。",
    notes: "擴大社群聲量與品牌信任度。",
    status: "pending",
    dueDate: new Date("2026-12-31"),
    sortOrder: 34,
  },
  {
    title: "大規模推廣：廣告投放、KOL 合作與媒體發稿",
    category: "marketing",
    description: "投放宣傳廣告、操作短影音擴散，啟動創作者/KOL 合作與新聞媒體稿發布。",
    notes: "引導大量人流關注首場活動。",
    status: "pending",
    dueDate: new Date("2026-12-31"),
    sortOrder: 35,
  },
  {
    title: "分波段公佈入選攤商名單與製作聯繫手冊",
    category: "vendor",
    description: "分波段揭露特色攤商，吸引粉絲關注；建立入選攤商專屬通訊群組與聯繫手冊。",
    notes: "重點產出：最終攤商名單與聯繫手冊。",
    status: "pending",
    dueDate: new Date("2026-12-31"),
    sortOrder: 36,
  },
  {
    title: "公共意外責任險投保與清潔規定制定",
    category: "operation",
    description: "完成公共意外責任險投保，制定活動垃圾分類、集中清運與清潔人員排班計畫。",
    notes: "確保活動符合法規與安全衛生規範。",
    status: "pending",
    dueDate: new Date("2026-12-31"),
    sortOrder: 37,
  },

  // ==================== 01月：最後校準與壓力測試月 ====================
  {
    title: "現場電力配置圖與安全評估報告定案",
    category: "operation",
    description: "確認現場電力配置、各攤位電箱迴路、安全負載與水電技師當天待命排班。",
    notes: "重點產出：電力配置圖與安全評估報告。",
    status: "pending",
    dueDate: new Date("2027-01-31"),
    sortOrder: 38,
  },
  {
    title: "硬體設備清點（帳篷、桌椅、燈光、音響）",
    category: "operation",
    description: "統籌所有租借硬體到場時間、數量點交與備用耗材清查。",
    notes: "確保所有硬體物料無短缺。",
    status: "pending",
    dueDate: new Date("2027-01-31"),
    sortOrder: 39,
  },
  {
    title: "攤位配置圖定案與進撤場 SOP 制定",
    category: "operation",
    description: "完成攤位最終座標配置圖、分批進場梯次、車輛引導與撤場恢復 SOP。",
    notes: "重點產出：攤位配置圖與進撤場 SOP。",
    status: "pending",
    dueDate: new Date("2027-01-31"),
    sortOrder: 40,
  },
  {
    title: "工作人員與志工教育訓練手冊與流程培訓",
    category: "operation",
    description: "完成工作人員手冊製作，進行現場志工培訓，熟悉活動流程、各組對接窗口與異常處理機制。",
    notes: "重點產出：工作人員/志工手冊與任務分配表。",
    status: "pending",
    dueDate: new Date("2027-01-31"),
    sortOrder: 41,
  },
  {
    title: "全流程模擬推演（壓力測試，確保零失誤）",
    category: "operation",
    description: "針對攤商、場地、硬體、用電與人流阻塞進行現場流程全盤模擬推演。",
    notes: "提前發現盲點並建立應變方案。",
    status: "pending",
    dueDate: new Date("2027-01-31"),
    sortOrder: 42,
  },
  {
    title: "幕後籌備紀錄持續曝光（倒數計時造勢）",
    category: "marketing",
    description: "持續更新幕後籌備花絮（Behind the scenes），保持活動熱度直至正式開幕。",
    notes: "營造現場興奮感與朝聖期待。",
    status: "pending",
    dueDate: new Date("2027-01-31"),
    sortOrder: 43,
  },

  // ==================== 02月：細節落地與正式舉行月 ====================
  {
    title: "場地細部配置與施工動線定案（含舞台與電力）",
    category: "design",
    description: "完成最終版場地詳細配置圖，精確標註攤位座標、電力配送點、舞台位置與主要觀展動線。",
    notes: "重點產出：最終版場地配置圖（含電力與動線）。",
    status: "pending",
    dueDate: new Date("2027-02-28"),
    sortOrder: 44,
  },
  {
    title: "場地路權行政申請與最終許可確認",
    category: "operation",
    description: "確認所有路權許可、場地租借核准函與相關公文備查完畢。",
    notes: "行政手續 100% 完備。",
    status: "pending",
    dueDate: new Date("2027-02-28"),
    sortOrder: 45,
  },
  {
    title: "工作人員與志工分組名冊與任務分配表定案",
    category: "operation",
    description: "完成工作人員與現場志工的分組招募、工作手冊發放與各時段崗位職責分配。",
    notes: "重點產出：工作人員/志工手冊與任務分配表。",
    status: "pending",
    dueDate: new Date("2027-02-28"),
    sortOrder: 46,
  },
  {
    title: "市集現場營運指揮與攤位引導執行",
    category: "operation",
    description: "執行現場營運指揮、攤商報到引導、人流流速管理與突發狀況排解。",
    notes: "確保現場動線流暢無阻。",
    status: "pending",
    dueDate: new Date("2027-02-28"),
    sortOrder: 47,
  },
  {
    title: "嚴格進撤場管理與場地清潔復原",
    category: "operation",
    description: "嚴格執行分梯進撤場 SOP，確保場地清潔復原與保證金無扣款退還。",
    notes: "維持主辦單位良好信譽。",
    status: "pending",
    dueDate: new Date("2027-02-28"),
    sortOrder: 48,
  },
  {
    title: "現場即時危機應變處置（設備/天候/人流）",
    category: "operation",
    description: "針對現場設備異常、天氣變化或突發事故進行即時應變與指揮。",
    notes: "保持危機應變小組隨時待命。",
    status: "pending",
    dueDate: new Date("2027-02-28"),
    sortOrder: 49,
  },
  {
    title: "活動全程影像紀錄與社群即時互動（Reels/Stories）",
    category: "marketing",
    description: "全程專業攝影錄影，捕捉市集氛圍與攤商互動；即時發布限時動態短片營造熱鬧氛圍。",
    notes: "重點產出：活動現場影像素材庫（精選照片與短片）。",
    status: "pending",
    dueDate: new Date("2027-02-28"),
    sortOrder: 50,
  },

  // ==================== 03月：數據回收與復盤月 ====================
  {
    title: "攤商問卷調查、銷售與人流數據分析",
    category: "curation",
    description: "收集攤商營收表現、問卷滿意度調查、現場人流與消費者回饋進行量化綜合分析。",
    notes: "用數據說話，找出關鍵成長點。",
    status: "pending",
    dueDate: new Date("2027-03-31"),
    sortOrder: 51,
  },
  {
    title: "產出首場市集結案報告 (Wrap-up Report)",
    category: "curation",
    description: "完成系統化結案報告，彙整全案成效、品牌聲量與數據，作為未來招商與政府青創補助之核心實績。",
    notes: "重點產出：首場市集結案報告 (Wrap-up Report)。",
    status: "pending",
    dueDate: new Date("2027-03-31"),
    sortOrder: 52,
  },
  {
    title: "最終財務清算與利潤結算 (P&L Final)",
    category: "curation",
    description: "清算最終預算執行狀況，核對所有收入與支出，執行公積金提撥與股東利潤分紅。",
    notes: "重點產出：最終財務結報表。",
    status: "pending",
    dueDate: new Date("2027-03-31"),
    sortOrder: 53,
  },
  {
    title: "團隊檢討復盤會議與下一屆改善清單",
    category: "curation",
    description: "召開團隊全面檢討會，針對流程、分工、危機處置等細項復盤，產出優缺點改善清單，「下次一定更好」。",
    notes: "重點產出：團隊內部改善清單（優點與待改進項）。",
    status: "pending",
    dueDate: new Date("2027-03-31"),
    sortOrder: 54,
  },

  // ==================== 04月：細節落地與供應商合約確認 ====================
  {
    title: "攤商說明會籌辦與行前通知發放",
    category: "vendor",
    description: "舉行攤商線上/線下說明會，詳細說明進撤場梯次、用電規範、現場動線與注意事項，發放行前通知單。",
    notes: "確保所有參展品牌充分理解現場營運規範與美學要求。",
    status: "pending",
    dueDate: new Date("2027-04-30"),
    sortOrder: 55,
  },
  {
    title: "全面確認所有供應商合約與物料期程",
    category: "operation",
    description: "與帳篷棚架、水電、流動廁所、音響、垃圾清運等協力廠商進行最終合約確認與進場時刻表核定。",
    notes: "落實硬體供應鏈無死角對接。",
    status: "pending",
    dueDate: new Date("2027-04-30"),
    sortOrder: 56,
  },
];

export const OFFICIAL_RESOURCE_FOLDERS = [
  {
    name: "品牌與 CIS 視覺",
    description: "品牌故事、Slogan、CIS 視覺手冊、Linktree 與線上試算表",
    items: [
      {
        kind: "link" as const,
        title: "官方 Google 試算表（執行藍圖時間軸）",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "主辦團隊共用執行藍圖、分工表與關鍵 Checklist 原表",
      },
      {
        kind: "link" as const,
        title: "咻一下市集 Linktree 整合頁面",
        linkUrl: "https://linktr.ee/hangoutmarket",
        note: "官方品牌對外多連結導流頁",
      },
      {
        kind: "link" as const,
        title: "品牌 CIS 視覺規範與 Slogan 手冊",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "沙漏造型商標（黑白版）、標準字體、CMYK色票、Slogan「陪你在快節奏的生活裡，咻一下。」",
      },
    ],
  },
  {
    name: "招商與法務規範",
    description: "共同創辦人協議、51% 股權協議書、市集規範書與攤商合約",
    items: [
      {
        kind: "link" as const,
        title: "共同創辦人協議書（組織章程）",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "確立股權比例、發起人 51% 絕對主導權、一票否決權與退場機制",
      },
      {
        kind: "link" as const,
        title: "市集營運管理規範書 (PDF 規範)",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "含違規罰則、美學要求、請假機制、天災停市與退費條款",
      },
      {
        kind: "link" as const,
        title: "攤商合作合約書與報名簡章",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "正式招商 Deck、報名表單與保證金規範",
      },
    ],
  },
  {
    name: "財務與商業模式",
    description: "BMC 九宮格、SWOT 分析、損益表 P&L 與盈餘分配機制",
    items: [
      {
        kind: "link" as const,
        title: "商業九宮格 (BMC) 與 SWOT 競爭優勢分析",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "確立核心價值主張（Why us?）與室內設計團隊空間美學優勢",
      },
      {
        kind: "link" as const,
        title: "首場市集預算損益表 (P&L) 與盈餘分配規則",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "公積金提撥、勞務津貼核發規則與股東年度淨利分紅機制",
      },
    ],
  },
  {
    name: "場地與硬體工程",
    description: "場地清單、電力配置圖、協力廠商清冊與進撤場 SOP",
    items: [
      {
        kind: "link" as const,
        title: "首展 Top 3 場地分析表與租借合約",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "學校/商圈/戶外場地費用、音量限制、用電上限與避開考試連假對策",
      },
      {
        kind: "link" as const,
        title: "現場電力配置圖與協力廠商聯繫清冊",
        linkUrl: "https://docs.google.com/spreadsheets/d/1JrRlc-qfEQDmQ2rWRAH5Yk9pkGWOPrq_/edit?gid=489205428#gid=489205428",
        note: "棚架桌椅、發電機、流動廁所、垃圾清運與公共意外責任險投保",
      },
    ],
  },
];
